export * from './GenresPage/GenresPage'
export * from './MovieDetailsPage/MovieDetailsPage'
export * from './MoviesPage/MoviesPage'
export * from './GenreMoviePage/GenreMoviePage'
export * from './NotFoundPage/NotFoundPage'